name: portcheck
description: A command line application for checking open/closed ports in your infrastructure.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  yamltools: ^1.1.1
dependencies:
  args: ^2.3.0
  udp: ^5.0.1
  version: ^2.0.0
