name: CI

on:
  push:
  pull_request:

jobs:
  dart_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: portcheck.linux
          - os: macOS-latest
            output-name: portcheck.mac
          - os: windows-latest
            output-name: portcheck.windows.exe

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool
            .packages
          key: ${{ runner.os }}-dart-${{ hashFiles('pubspec.lock') }}
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
      - run: mkdir build
      - name: build
        run: dart compile exe bin/portcheck.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output-name }}
          path: build/${{ matrix.output-name }}
